import {
  mdiSilverwareVariant, mdiCar, mdiShopping, mdiLightningBolt, mdiCash, mdiTagOutline,
  mdiCoffee, mdiHome, mdiHeart, mdiDumbbell, mdiBookOpenVariant, mdiMusic,
  mdiTelevision, mdiCellphone, mdiMonitor, mdiGiftOutline, mdiAirplane, mdiBed,
  mdiTrain, mdiBus, mdiBicycle, mdiFuel, mdiHospitalBox, mdiPill,
  mdiTshirtCrew, mdiWatch, mdiDiamond, mdiCrown, mdiStar, mdiWeatherSunny,
  mdiWeatherNight, mdiCloud, mdiUmbrella, mdiLeaf, mdiFire, mdiWater,
  mdiSnowflake, mdiHeadphones, mdiCamera, mdiFilm, mdiMessageOutline, mdiPhone,
  mdiEmailOutline, mdiMapMarker, mdiCompass, mdiEarth, mdiClockOutline, mdiBellOutline,
  mdiShieldOutline, mdiKey, mdiWrench, mdiCog, mdiAccount, mdiBriefcase,
  mdiSchool, mdiFlower, mdiContentCut, mdiPrinter, mdiOfficeBuilding, mdiStore,
  mdiPalette, mdiPineTree, mdiPaw, mdiGamepadVariant, mdiGondola, mdiTent,
  mdiSailBoat, mdiCastle, mdiRocketLaunch, mdiLightbulbOnOutline, mdiGlassWine,
  mdiCakeVariant, mdiPizza, mdiApple,
} from "@mdi/js";
import MdiIcon from "../components/MdiIcon";
import type { FunctionComponent } from "react";

type IconComponent = FunctionComponent<{ className?: string }>;

function wrap(path: string): IconComponent {
  return ({ className }) => <MdiIcon path={path} className={className} />;
}

export const iconMap: Record<string, IconComponent> = {
  Utensils: wrap(mdiSilverwareVariant),
  Car: wrap(mdiCar),
  ShoppingBag: wrap(mdiShopping),
  Zap: wrap(mdiLightningBolt),
  Banknote: wrap(mdiCash),
  Tag: wrap(mdiTagOutline),
  Coffee: wrap(mdiCoffee),
  Home: wrap(mdiHome),
  Heart: wrap(mdiHeart),
  Dumbbell: wrap(mdiDumbbell),
  Book: wrap(mdiBookOpenVariant),
  Music: wrap(mdiMusic),
  Tv: wrap(mdiTelevision),
  Smartphone: wrap(mdiCellphone),
  Monitor: wrap(mdiMonitor),
  Gift: wrap(mdiGiftOutline),
  Plane: wrap(mdiAirplane),
  Hotel: wrap(mdiBed),
  Train: wrap(mdiTrain),
  Bus: wrap(mdiBus),
  Bike: wrap(mdiBicycle),
  Fuel: wrap(mdiFuel),
  Hospital: wrap(mdiHospitalBox),
  Pill: wrap(mdiPill),
  Shirt: wrap(mdiTshirtCrew),
  Watch: wrap(mdiWatch),
  Gem: wrap(mdiDiamond),
  Crown: wrap(mdiCrown),
  Star: wrap(mdiStar),
  Sun: wrap(mdiWeatherSunny),
  Moon: wrap(mdiWeatherNight),
  Cloud: wrap(mdiCloud),
  Umbrella: wrap(mdiUmbrella),
  Leaf: wrap(mdiLeaf),
  Flame: wrap(mdiFire),
  Droplet: wrap(mdiWater),
  Snowflake: wrap(mdiSnowflake),
  Headphones: wrap(mdiHeadphones),
  Camera: wrap(mdiCamera),
  Film: wrap(mdiFilm),
  MessageCircle: wrap(mdiMessageOutline),
  Phone: wrap(mdiPhone),
  Mail: wrap(mdiEmailOutline),
  MapPin: wrap(mdiMapMarker),
  Compass: wrap(mdiCompass),
  Globe: wrap(mdiEarth),
  Clock: wrap(mdiClockOutline),
  Bell: wrap(mdiBellOutline),
  Shield: wrap(mdiShieldOutline),
  Key: wrap(mdiKey),
  Wrench: wrap(mdiWrench),
  Settings: wrap(mdiCog),
  User: wrap(mdiAccount),
  Briefcase: wrap(mdiBriefcase),
  GraduationCap: wrap(mdiSchool),
  Flower: wrap(mdiFlower),
  Scissors: wrap(mdiContentCut),
  Printer: wrap(mdiPrinter),
  Building: wrap(mdiOfficeBuilding),
  Store: wrap(mdiStore),
  Palette: wrap(mdiPalette),
  TreePine: wrap(mdiPineTree),
  PawPrint: wrap(mdiPaw),
  Gamepad2: wrap(mdiGamepadVariant),
  CableCar: wrap(mdiGondola),
  Tent: wrap(mdiTent),
  Sailboat: wrap(mdiSailBoat),
  Castle: wrap(mdiCastle),
  Rocket: wrap(mdiRocketLaunch),
  Lightbulb: wrap(mdiLightbulbOnOutline),
  Wine: wrap(mdiGlassWine),
  CakeSlice: wrap(mdiCakeVariant),
  Pizza: wrap(mdiPizza),
  Apple: wrap(mdiApple),
};

export const iconNames = Object.keys(iconMap);